apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
spec:
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: API_PORT
              value: "{{ .Values.apiPort }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
  replicas: {{ .Values.replicaCount }}
