apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.targetPort }}
      protocol: {{ .Values.protocol }}
      name: {{ .Values.serviceName }}
  type: {{ .Values.serviceType }}
