apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appphyton-ingress
  #annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: apppython
    http:
      paths:
      - path: /api/v1/(.*)
        pathType: Prefix
        backend:
          service:
            name: appphyton
            port:
              number: 8081
