apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apppython-minikube.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
    - host:  {{ .Values.ingress.host}}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apppython-minikube-rollout
                port:
                  number: 8081

