apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apppython.fullname" . }}
spec:
  ingressClassName: nginx #sin esta anotacion eks no asocia ALB a el ingress del cluster
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "apppython.name" . }}
                port:
                  number: {{ .Values.servicePort }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
