apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apppython
  namespace: argocd
spec:
  source:
    path: apppython/k8s-test # the k8s source files 
    repoURL: https://github.com/garrijuan/app-python-CICD.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc' #cluster monitoring
    namespace: kube-system #namespace where we want to deploy
  project: default