apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=garrijuan/test_api_python
    argocd-image-updater.argoproj.io/myalias.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/myalias.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest
  name: apppython
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  source:
    path: HELM/apppython #apppython/k8s-test # the k8s source files 
    repoURL: https://github.com/garrijuan/app-python-CICD.git
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc' #cluster monitoring
    namespace: default #namespace where we want to deploy
  project: default