apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-rollout
  namespace: staging
spec:
  replicas: 3
  #revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: my-app-rollout
  template:
    metadata:
      labels:
        app: my-app-rollout
    spec:
      containers:
      - name: my-app-container
        image: garrijuan/test_api_python:f9c101f
        ports:
        - containerPort: 8080
  strategy:
    canary:
      #canaryService: my-app-rollout
      #stableService: apppython-minikube
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 100