name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: python Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r appPython/app/requirements.txt

      - name: Run tests
        run: |
          python3 -m unittest appPython/test/test_main.py
### generar imagen docker y repositarla
  build_and_push_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t test_api_python .

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: docker tag test_api_python ${{ secrets.DOCKER_USERNAME }}/test_api_python:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test_api_python:latest
