name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: python Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r appPython/app/requirements.txt

      - name: Run tests
        run: |
          python3 -m unittest appPython/test/test_main.py
